---
- name: Install build server
  hosts: build
  tasks:
    - name: install packages
      apt:
        name: '{{ item }}'
        state: present
        update_cache: yes
      loop:
        - openjdk-8-jdk
        - git
        - maven

    - name: fetch code
      git:
        repo: https://github.com/boxfuse/boxfuse-sample-java-war-hello.git
        dest: /opt/boxfuse

    - name: mvn package
      shell:
        cmd: mvn package
        chdir: /opt/boxfuse/

    - name: copy private key
      copy: 
        src: ./terraform-key.pem
        dest: /opt/
        mode:'0644'

- name: install prod server
  hosts: prod
  tasks:
    - name: install packages
      apt:
        name: '{{ item }}'
        state: present
        update_cache: yes
      loop:
        - openjdk-8-jdk

    - name: create tomcat directory
      file:
        path: /usr/local/tomcat
        state: directory

    - name: download tomcat
      unarchive:
        src: https://archive.apache.org/dist/tomcat/tomcat-8/v8.5.41/bin/apache-tomcat-8.5.41.tar.gz
        dest: /usr/local/tomcat
        extra_opts: [--strip-components=1]
        remote_src: yes

    - name: Cleen ROOT folder
      file:
        path: /usr/local/tomcat/webapps/ROOT
        state: absent

#     - name: Get artifact from build server
#       synchronize:
#         src: /opt/boxfuse/target/hello-1.0.war
#         dest: /usr/local/tomcat/webapps/ROOT.war
#         mode: push
#       delegate_to: build
# FROM alpine:latest
# RUN apk update && apk add openjdk8
# RUN wget https://archive.apache.org/dist/tomcat/tomcat-8/v8.5.41/bin/apache-tomcat-8.5.41.tar.gz
# RUN tar -xzvf apache-tomcat-8.5.41.tar.gz && rm -rf apache-tomcat-8.5.41.tar.gz && mv apache-tomcat-8.5.41 /usr/local/tomcat
# RUN rm -rf /usr/local/tomcat/webapps/ROOT
# COPY --from=BUILD_SERVER /boxfuse-sample-java-war-hello/target/hello-1.0.war /usr/local/tomcat/webapps/ROOT.war
# WORKDIR /usr/local/tomcat
# EXPOSE 8080
# ENTRYPOINT ["/usr/local/tomcat/bin/catalina.sh","run"]

