---
- name: INSTALL BUILD SERVER
  hosts: build
  tasks:
    - name: install packages
      apt:
        name: '{{ item }}'
        state: present
        update_cache: yes
      loop:
        - openjdk-8-jdk
        - git
        - maven

    - name: fetch code
      git:
        repo: https://github.com/boxfuse/boxfuse-sample-java-war-hello.git
        dest: /opt/boxfuse

    - name: mvn package
      shell:
        cmd: mvn package
        chdir: /opt/boxfuse/

    - name: fetch artifact
      fetch:
        src: /opt/boxfuse/target/hello-1.0.war
        dest: ./
        flat: yes

- name: INSTALL PROD
  hosts: prod
  tasks:
    - name: Install tomcat
      apt:
        name: '{{ item }}'
        state: present
        update_cache: yes
      loop:
        - openjdk-11-jdk
        - wget
        - tar

    - name: create tomcat user
      user:
        name: tomcat
        state: present
        shell: /bin/false
        home: /opt/tomcat

    - name: download tomcat
      unarchive:
        src: https://dlcdn.apache.org/tomcat/tomcat-10/v10.1.5/bin/apache-tomcat-10.1.5.tar.gz
        dest: /opt/tomcat
        extra_opts: [--strip-components=1]
        remote_src: yes

    - name: change ownership
      file:
        path: /opt/tomcat
        state: directory
        recurse: yes
        owner: tomcat
        group: tomcat

    - name: change permission
      file:
        path: /opt/tomcat/bin
        state: directory
        recurse: yes
        mode: '0777'

    - name: copy tomcat.service
      synchronize:
        src: tomcat.service
        dest: /etc/systemd/system/tomcat.service
      notify: start & enable tomcat & daemon-reload

    # - name: clean ROOT folder
    #   file:
    #     path: /var/lib/tomcat9/webapps/ROOT
    #     state: absent

    # - name: transfer artifact to prod
    #   synchronize:
    #     src: ./hello-1.0.war
    #     dest: /var/lib/tomcat9/webapps/ROOT.war
    #   notify:
    #     - restart tomcat

  handlers:
    - name: restart tomcat
      service:
        name: tomcat
        state: restarted

    - name: start tomcat
      service:
        name: tomcat
        state: started

    - name: start & enable tomcat & daemon-reload
      systemd:
        name: tomcat
        state: started
        enabled: true
        daemon_reload: true

      # - name: start tomcat
      #   command: "{{ item }}"
      #   loop:
      #     - bash /usr/local/tomcat/bin/catalina.sh

      # - name: install packages
      #   apt:
      #     name: '{{ item }}'
      #     state: present
      #     update_cache: yes
      #   loop:
      #     - openjdk-8-jdk

      # - name: create tomcat directory
      #   file:
      #     path: /usr/local/tomcat
      #     state: directory

      # - name: Cleen ROOT folder
      #   file:
      #     path: /usr/local/tomcat/webapps/ROOT
      #     state: absent

      # - name: transfer artifact to prod
      #   synchronize:
      #     src: ./hello-1.0.war
      #     dest: /usr/local/tomcat/webapps/ROOT.war

      # - name: start tomcat
      #   command: "{{ item }}"
      #   loop:
      #     - bash /usr/local/tomcat/bin/catalina.sh
