---
- name: DevOps
  hosts: build
  tasks:
    - name: install packages
      apt:
        name: '{{ item }}'
        state: present
        update_cache: yes
      loop:
        - openjdk-8-jdk
        - git
        - maven

    - name: fetch code
      git:
        repo: https://github.com/boxfuse/boxfuse-sample-java-war-hello.git
        dest: /tmp/boxfuse

    - name: mvn package
      shell:
        cmd: mvn package
        chdir: /tmp/
# FROM alpine:latest as BUILD_SERVER
# RUN apk update && apk add openjdk8 && apk add maven && apk add git
# RUN git clone https://github.com/boxfuse/boxfuse-sample-java-war-hello.git
# RUN cd boxfuse-sample-java-war-hello && mvn package
