---
- name: Build
  hosts: build
  tasks:
    - name: install packages
      apt:
        name: '{{ item }}'
        state: present
        update_cache: yes
      loop:
        - openjdk-8-jdk
        - git
        - maven

    - name: fetch code
      git:
        repo: https://github.com/boxfuse/boxfuse-sample-java-war-hello.git
        dest: /opt/boxfuse

    - name: mvn package
      shell:
        cmd: mvn package
        chdir: /opt/boxfuse/

- name: Prod
  hosts: Prod
  tasks:
    - name: install packages
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      loop:
        - openjdk-8-jdk

# FROM alpine:latest
# RUN apk update && apk add openjdk8
# RUN wget https://archive.apache.org/dist/tomcat/tomcat-8/v8.5.41/bin/apache-tomcat-8.5.41.tar.gz
# RUN tar -xzvf apache-tomcat-8.5.41.tar.gz && rm -rf apache-tomcat-8.5.41.tar.gz && mv apache-tomcat-8.5.41 /usr/local/tomcat 
# RUN rm -rf /usr/local/tomcat/webapps/ROOT
# COPY --from=BUILD_SERVER /boxfuse-sample-java-war-hello/target/hello-1.0.war /usr/local/tomcat/webapps/ROOT.war
# WORKDIR /usr/local/tomcat
# EXPOSE 8080
# ENTRYPOINT ["/usr/local/tomcat/bin/catalina.sh","run"]




