version: "3"
services:
  tomcat: 
    build: 
      context: .
    ports:
      - "9000:8080"
    container_name: tomcat9
    volumes:
      - web-apps:/usr/local/tomcat/webapps

volumes:
  aweb-apps: